# Export Terraform variable values to an Ansible var_file
resource "local_file" "tf_ansible_vars_file" {
  content = <<-DOC
    # Ansible vars_file containing variable values from Terraform.
    # Generated by Terraform mgmt configuration.

    tunnel_id: ${cloudflare_argo_tunnel.all_the_things.id}
    account: ${var.cloudflare_account_id}
    tunnel_name: ${cloudflare_argo_tunnel.all_the_things.name}
    secret: ${random_id.tunnel_secret.b64_std}
    zone: ${var.cloudflare_zone}
    DOC
  filename = "./tf_ansible_vars_file.yml"
}